# Generated by Django 2.2.4 on 2022-01-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220114_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_title',
            new_name='title',
        ),
    ]
